[package]
name = "firestore-type-generator"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "fitype"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
clap-serde = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
