name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/firegen dist/
          cd dist
          tar -czf ../firegen-${{ matrix.target }}.tar.gz firegen

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: firegen-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
