name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/fitype dist/
          cd dist
          tar -czf ../fitype-${{ matrix.target }}.tar.gz fitype

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: fitype-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
